language: python
sudo: false
python:
    - 2.7
install:
    - pip install -U setuptools==33.1.1
    - pip install zc.buildout
    - pip install -U coverage coveralls
    - pip install -U six
    - buildout bootstrap
    - buildout
script:
    - coverage run bin/test -v1
after_success:
    - coveralls
notifications:
    email: false
cache:
  pip: true
  directories:
    - eggs/
